<?php

namespace SNT\ServiceBundle\Repository;

/**
 * EmployersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployersRepository extends \Doctrine\ORM\EntityRepository
{
}
